In [1]:
import numpy as np
import torch

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 1.2521,  1.8877,  1.1725],
        [-1.4543, -0.6936, -1.1333]], requires_grad=True)
tensor([-1.1569,  0.5500], requires_grad=True)


In [6]:
def model(x):
    return x @ w.t() + b

In [7]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 267.1409, -200.8217],
        [ 353.9437, -265.3650],
        [ 428.7355, -284.6552],
        [ 251.1101, -219.5509],
        [ 348.5353, -245.7180]], grad_fn=<AddBackward0>)


In [8]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [10]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(90863.5078, grad_fn=<DivBackward0>)


In [11]:
# Compute gradients
loss.backward()

In [12]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[ 1.2521,  1.8877,  1.1725],
        [-1.4543, -0.6936, -1.1333]], requires_grad=True)
tensor([[ 21501.8633,  22618.6367,  14035.3320],
        [-28155.7891, -30479.1191, -18867.8691]])


In [13]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [14]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 267.1409, -200.8217],
        [ 353.9437, -265.3650],
        [ 428.7355, -284.6552],
        [ 251.1101, -219.5509],
        [ 348.5353, -245.7180]], grad_fn=<AddBackward0>)


In [15]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(90863.5078, grad_fn=<DivBackward0>)


In [16]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ 21501.8633,  22618.6367,  14035.3320],
        [-28155.7891, -30479.1191, -18867.8691]])
tensor([ 253.6931, -335.2222])


In [17]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [18]:
print(w)
print(b)

tensor([[ 1.0370,  1.6615,  1.0322],
        [-1.1728, -0.3888, -0.9446]], requires_grad=True)
tensor([-1.1594,  0.5534], requires_grad=True)


In [19]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(61284.3945, grad_fn=<DivBackward0>)


In [20]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [21]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(78.1838, grad_fn=<DivBackward0>)


In [22]:
# Predictions
preds

tensor([[ 59.3486,  72.2963],
        [ 82.1618,  94.8146],
        [115.2817, 143.0828],
        [ 34.7591,  47.2877],
        [ 93.6290, 103.0686]], grad_fn=<AddBackward0>)

In [23]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [24]:
# Train for 100 epochs
for i in range(1000):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [25]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(7.8776, grad_fn=<DivBackward0>)


In [26]:
# Predictions
preds

tensor([[ 57.0585,  70.7175],
        [ 81.6104,  97.9997],
        [120.2175, 138.3772],
        [ 21.5498,  38.5384],
        [100.3780, 113.7156]], grad_fn=<AddBackward0>)

In [27]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [28]:
import torch.nn as nn

In [29]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [30]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [31]:
from torch.utils.data import TensorDataset

In [32]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [33]:
from torch.utils.data import DataLoader

In [34]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [37]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 91.,  88.,  64.],
        [ 91.,  87.,  65.],
        [101.,  44.,  37.],
        [ 73.,  67.,  43.],
        [ 92.,  87.,  64.]])
tensor([[ 81., 101.],
        [ 80., 102.],
        [ 21.,  38.],
        [ 56.,  70.],
        [ 82., 100.]])


In [38]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.2255, -0.2624, -0.4539],
        [-0.0435,  0.2895,  0.5474]], requires_grad=True)
Parameter containing:
tensor([-0.5496, -0.3281], requires_grad=True)


In [39]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.2255, -0.2624, -0.4539],
         [-0.0435,  0.2895,  0.5474]], requires_grad=True),
 Parameter containing:
 tensor([-0.5496, -0.3281], requires_grad=True)]

In [40]:
# Generate predictions
preds = model(inputs)
preds

tensor([[-54.1069,  39.4277],
        [-73.2070,  56.2184],
        [-81.6506,  66.4245],
        [-51.6272,  27.9340],
        [-73.0675,  62.7757],
        [-54.0701,  39.0947],
        [-73.3984,  56.4762],
        [-82.3299,  66.9284],
        [-51.6640,  28.2670],
        [-73.2958,  63.3666],
        [-54.2984,  39.6856],
        [-73.1701,  55.8854],
        [-81.4591,  66.1666],
        [-51.3989,  27.3432],
        [-73.1043,  63.1087]], grad_fn=<AddmmBackward0>)

In [41]:
# Import nn.functional
import torch.nn.functional as F

In [42]:
# Define loss function
loss_fn = F.mse_loss

In [43]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(12298.6660, grad_fn=<MseLossBackward0>)


In [44]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [45]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(12298.6660, grad_fn=<MseLossBackward0>)


In [46]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [47]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 185.5686
Epoch [20/100], Loss: 193.8278
Epoch [30/100], Loss: 138.6139
Epoch [40/100], Loss: 75.6463
Epoch [50/100], Loss: 47.3090
Epoch [60/100], Loss: 32.4450
Epoch [70/100], Loss: 27.6686
Epoch [80/100], Loss: 35.7375
Epoch [90/100], Loss: 41.9195
Epoch [100/100], Loss: 22.6539


In [48]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 15.5239
Epoch [20/100], Loss: 12.5192
Epoch [30/100], Loss: 16.0196
Epoch [40/100], Loss: 4.1675
Epoch [50/100], Loss: 15.9893
Epoch [60/100], Loss: 13.9032
Epoch [70/100], Loss: 5.3639
Epoch [80/100], Loss: 7.4514
Epoch [90/100], Loss: 11.4401
Epoch [100/100], Loss: 6.2343


In [49]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 7.5710
Epoch [20/100], Loss: 7.4063
Epoch [30/100], Loss: 7.7155
Epoch [40/100], Loss: 6.7594
Epoch [50/100], Loss: 12.7679
Epoch [60/100], Loss: 6.2213
Epoch [70/100], Loss: 7.7336
Epoch [80/100], Loss: 3.6051
Epoch [90/100], Loss: 5.7488
Epoch [100/100], Loss: 1.7007


In [50]:
fit(1000, model, loss_fn, opt, train_dl)

Epoch [10/1000], Loss: 3.8704
Epoch [20/1000], Loss: 5.8148
Epoch [30/1000], Loss: 2.0040
Epoch [40/1000], Loss: 3.7599
Epoch [50/1000], Loss: 3.9741
Epoch [60/1000], Loss: 5.0130
Epoch [70/1000], Loss: 3.1328
Epoch [80/1000], Loss: 4.2960
Epoch [90/1000], Loss: 2.0919
Epoch [100/1000], Loss: 4.0252
Epoch [110/1000], Loss: 1.6960
Epoch [120/1000], Loss: 2.3508
Epoch [130/1000], Loss: 2.4901
Epoch [140/1000], Loss: 1.3746
Epoch [150/1000], Loss: 3.1334
Epoch [160/1000], Loss: 0.6770
Epoch [170/1000], Loss: 2.2434
Epoch [180/1000], Loss: 3.3843
Epoch [190/1000], Loss: 2.4984
Epoch [200/1000], Loss: 1.2138
Epoch [210/1000], Loss: 2.0722
Epoch [220/1000], Loss: 1.7791
Epoch [230/1000], Loss: 2.7938
Epoch [240/1000], Loss: 1.9253
Epoch [250/1000], Loss: 1.5004
Epoch [260/1000], Loss: 2.2314
Epoch [270/1000], Loss: 1.8976
Epoch [280/1000], Loss: 2.8042
Epoch [290/1000], Loss: 1.0874
Epoch [300/1000], Loss: 1.4399
Epoch [310/1000], Loss: 2.1316
Epoch [320/1000], Loss: 1.2601
Epoch [330/1000],

In [51]:
fit(1000, model, loss_fn, opt, train_dl)

Epoch [10/1000], Loss: 1.3563
Epoch [20/1000], Loss: 1.1963
Epoch [30/1000], Loss: 0.8988
Epoch [40/1000], Loss: 0.9825
Epoch [50/1000], Loss: 0.9528
Epoch [60/1000], Loss: 1.1854
Epoch [70/1000], Loss: 0.7688
Epoch [80/1000], Loss: 0.7702
Epoch [90/1000], Loss: 0.8905
Epoch [100/1000], Loss: 0.8038
Epoch [110/1000], Loss: 1.4073
Epoch [120/1000], Loss: 0.8962
Epoch [130/1000], Loss: 1.1284
Epoch [140/1000], Loss: 1.2053
Epoch [150/1000], Loss: 0.9565
Epoch [160/1000], Loss: 1.1997
Epoch [170/1000], Loss: 0.9109
Epoch [180/1000], Loss: 1.1193
Epoch [190/1000], Loss: 1.3727
Epoch [200/1000], Loss: 1.5865
Epoch [210/1000], Loss: 1.1234
Epoch [220/1000], Loss: 0.9276
Epoch [230/1000], Loss: 0.9490
Epoch [240/1000], Loss: 1.2109
Epoch [250/1000], Loss: 1.4063
Epoch [260/1000], Loss: 1.1239
Epoch [270/1000], Loss: 0.9540
Epoch [280/1000], Loss: 0.7960
Epoch [290/1000], Loss: 1.3487
Epoch [300/1000], Loss: 0.9581
Epoch [310/1000], Loss: 0.7987
Epoch [320/1000], Loss: 1.2547
Epoch [330/1000],

In [52]:
fit(1000, model, loss_fn, opt, train_dl)

Epoch [10/1000], Loss: 0.6686
Epoch [20/1000], Loss: 1.1676
Epoch [30/1000], Loss: 1.0600
Epoch [40/1000], Loss: 1.4073
Epoch [50/1000], Loss: 1.2787
Epoch [60/1000], Loss: 1.0538
Epoch [70/1000], Loss: 1.2136
Epoch [80/1000], Loss: 0.9398
Epoch [90/1000], Loss: 0.9132
Epoch [100/1000], Loss: 0.9006
Epoch [110/1000], Loss: 0.7598
Epoch [120/1000], Loss: 1.5240
Epoch [130/1000], Loss: 1.0317
Epoch [140/1000], Loss: 0.8003
Epoch [150/1000], Loss: 1.4832
Epoch [160/1000], Loss: 0.9315
Epoch [170/1000], Loss: 0.9445
Epoch [180/1000], Loss: 0.8855
Epoch [190/1000], Loss: 1.0747
Epoch [200/1000], Loss: 0.6873
Epoch [210/1000], Loss: 1.0240
Epoch [220/1000], Loss: 0.7236
Epoch [230/1000], Loss: 1.5282
Epoch [240/1000], Loss: 1.3701
Epoch [250/1000], Loss: 1.0392
Epoch [260/1000], Loss: 0.9314
Epoch [270/1000], Loss: 1.2801
Epoch [280/1000], Loss: 1.3986
Epoch [290/1000], Loss: 0.8625
Epoch [300/1000], Loss: 0.8313
Epoch [310/1000], Loss: 0.8944
Epoch [320/1000], Loss: 1.4787
Epoch [330/1000],

In [53]:
fit(1000, model, loss_fn, opt, train_dl)

Epoch [10/1000], Loss: 1.3470
Epoch [20/1000], Loss: 1.0637
Epoch [30/1000], Loss: 0.7715
Epoch [40/1000], Loss: 0.9102
Epoch [50/1000], Loss: 1.3595
Epoch [60/1000], Loss: 1.2099
Epoch [70/1000], Loss: 1.1230
Epoch [80/1000], Loss: 0.9488
Epoch [90/1000], Loss: 0.6935
Epoch [100/1000], Loss: 0.7277
Epoch [110/1000], Loss: 1.4734
Epoch [120/1000], Loss: 1.4668
Epoch [130/1000], Loss: 1.1594
Epoch [140/1000], Loss: 0.7625
Epoch [150/1000], Loss: 1.1610
Epoch [160/1000], Loss: 0.7709
Epoch [170/1000], Loss: 0.8766
Epoch [180/1000], Loss: 1.2450
Epoch [190/1000], Loss: 1.4391
Epoch [200/1000], Loss: 0.7897
Epoch [210/1000], Loss: 1.5809
Epoch [220/1000], Loss: 0.9807
Epoch [230/1000], Loss: 1.2977
Epoch [240/1000], Loss: 1.5286
Epoch [250/1000], Loss: 1.2034
Epoch [260/1000], Loss: 0.9592
Epoch [270/1000], Loss: 0.6240
Epoch [280/1000], Loss: 1.5395
Epoch [290/1000], Loss: 0.8237
Epoch [300/1000], Loss: 0.9887
Epoch [310/1000], Loss: 1.2465
Epoch [320/1000], Loss: 0.8344
Epoch [330/1000],

In [54]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 56.8726,  70.3481],
        [ 82.1125, 100.5861],
        [118.2123, 132.8118],
        [ 20.8415,  37.7727],
        [101.8739, 118.5038],
        [ 55.6305,  69.2726],
        [ 81.9742, 100.6848],
        [118.5153, 133.4191],
        [ 22.0835,  38.8483],
        [102.9776, 119.6780],
        [ 56.7342,  70.4468],
        [ 80.8705,  99.5106],
        [118.3507, 132.7131],
        [ 19.7378,  36.5985],
        [103.1159, 119.5793]], grad_fn=<AddmmBackward0>)

In [55]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [56]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[53.4084, 67.5036]], grad_fn=<AddmmBackward0>)